apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: ttl.sh/wh_test1
  newTag: 1h
- name: controller-admission
  newName: IMG=admission-testme
  newTag: latest
