apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: example.com/kyma-workloads-webhook
  newTag: v0.0.1
- name: controller-admission
  newName: IMG=admission-testme
  newTag: latest
