apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/created-by: kyma-workloads-webhook
    app.kubernetes.io/part-of: kyma-workloads-webhook
    app.kubernetes.io/managed-by: kustomize
  name: kyma
  namespace: system
spec:
  commonName: kww-webhook-service.kww-system
  dnsNames:
  - kww-webhook-service.kww-system.svc
  isCA: true
  issuerRef:
    name: kyma
    namespace: system
  secretRef:
    name: snatch-certificates
    namespace: system
