# This configuration is for teaching kustomize how to update name ref substitution
nameReference:
- kind: Issuer
  group: cert.gardener.cloud
  fieldSpecs:
  - kind: Certificate
    group: cert.gardener.cloud
    path: spec/issuerRef/name

