namespace: kww-system
namePrefix: kww-

patches:
- path: manager_webhook_patch.yaml
- path: manager_metrics_patch.yaml
  target:
    kind: Deployment

resources:
- ../manager
- ../rbac
- ../webhook
- metrics_service.yaml
- ../certmanager

sortOptions:
  order: fifo
