namespace: kyma-system
namePrefix: snatch-

patches:
- path: manager_webhook_patch.yaml
- path: manager_metrics_patch.yaml
  target:
    kind: Deployment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kyma-worker-pool-name=snatch-test
  target:
    kind: Deployment

resources:
- ../manager
- ../rbac
- ../webhook
- metrics_service.yaml
- ../certmanager

sortOptions:
  order: fifo
